const VISIBILITY_BY_ROLE = {
    coordinator: ["DRAFT", "PENDING"],
    hod: ["PENDING"],
    principal: ["HOD_VERIFIED"],
    vice_principal: ["HOD_VERIFIED"],
    office: ["MANAGEMENT_APPROVED"]
};

const PROPOSAL_TRANSITIONS = {
    DRAFT: ["PENDING"],
    PENDING: ["HOD_VERIFIED"],
    HOD_VERIFIED: ["MANAGEMENT_APPROVED"],
    MANAGEMENT_APPROVED: ["ALLOCATED"]
};

const EXPENDITURE_TRANSITIONS = {
    PENDING: ["HOD_VERIFIED"],
    HOD_VERIFIED: ["MANAGEMENT_APPROVED"],
    MANAGEMENT_APPROVED: ["FINALIZED"]
};

module.exports = {
    VISIBILITY_BY_ROLE,
    PROPOSAL_TRANSITIONS,
    EXPENDITURE_TRANSITIONS
};
